Backend/Backend/Models/LeagueView.cs
using Dominio;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Backend.Models
{
    public class LeagueView: League
    {

        [Display(Name="Logo")]
        public HttpPostedFileBase LogoFile { get; set; }



    }
}

Backend/Backend/Controllers/LeaguesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dominio;
using Backend.Models;
using Backend.Helpers;

namespace Backend.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LeaguesController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Leagues
        public async Task<ActionResult> Index()
        {
            return View(await db.Leagues.ToListAsync());
        }

        // GET: Leagues/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = await db.Leagues.FindAsync(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        // GET: Leagues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Leagues/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeagueView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/Logos";

                if (view.LogoFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var league = ToLeague(view);
                league.Logo = pic;
                db.Leagues.Add(league);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        private League ToLeague(LeagueView league)
        {
            return new League
            {
                LeagueId = league.LeagueId,
                Logo = league.Logo,
                Name = league.Name,
                Teams = league.Teams
            };
        }

        // GET: Leagues/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = await db.Leagues.FindAsync(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            var view = ToView(league);

            return View(view);
        }

        private LeagueView ToView(League league)
        {
            return new LeagueView
            {
                LeagueId = league.LeagueId,
                Logo = league.Logo,
                Name = league.Name,
                Teams = league.Teams
            };
        }

        // POST: Leagues/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LeagueView view)
        {
            if (ModelState.IsValid)
            {
                var pic = view.Logo;
                var folder = "~/Content/Logos";

                if (view.LogoFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var league = ToLeague(view);
                league.Logo = pic;

                db.Entry(league).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }



            return View(view);
        }

        // GET: Leagues/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = await db.Leagues.FindAsync(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        // POST: Leagues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            League league = await db.Leagues.FindAsync(id);
            db.Leagues.Remove(league);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        #region Controladores de Team
        public ActionResult CreateTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var league = db.Leagues.Find(id);

            var team = new TeamView { LeagueId = league.LeagueId };

            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTeam(TeamView teamview)
        {
            var pic = string.Empty;
            var folder = "~/Content/Logos";

            if (teamview.LogoFile != null)
            {
                pic = FilesHelper.UploadPhoto(teamview.LogoFile, folder);
                pic = $"{folder}/{pic}";
            }

            teamview.Logo = pic;

            var team = new Team
            {
                LeagueId = teamview.LeagueId,
                Fans = teamview.Fans,
                Initials = teamview.Initials,
                League = teamview.League,
                Locals = teamview.Locals,
                Logo = teamview.Logo,
                Name = teamview.Name,
                Visitors = teamview.Visitors
            };

            if (ModelState.IsValid)
            {
                db.Teams.Add(team);
                await db.SaveChangesAsync();
                return RedirectToAction($"Details/{team.LeagueId}");
            }

            return View(teamview);
        }

        public ActionResult EditTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var team = db.Teams.Find(id);

            var teamview = new TeamView
            {
                LeagueId = team.LeagueId,
                Logo = team.Logo,
                Initials = team.Initials,
                Name = team.Name,
                TeamId = team.TeamId
            };

            return View(teamview);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditTeam(TeamView teamview)
        {
            var pic = teamview.Logo;
            var folder = "~/Content/Logos";

            if (teamview.LogoFile != null)
            {
                pic = FilesHelper.UploadPhoto(teamview.LogoFile, folder);
                pic = $"{folder}/{pic}";
            }

            teamview.Logo = pic;

            var team = new Team
            {
                LeagueId = teamview.LeagueId,
                Initials = teamview.Initials,
                Logo = teamview.Logo,
                Name = teamview.Name,
                TeamId = teamview.TeamId
            };

            if (ModelState.IsValid)
            {
                db.Entry(team).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction($"Details/{team.LeagueId}");
            }

            return View(teamview);
        }

        public async Task<ActionResult> DetailsTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = await db.Teams.FindAsync(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        public async Task<ActionResult> DeleteTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = await db.Teams.FindAsync(id);
            if (team == null)
            {
                return HttpNotFound();
            }

            db.Entry(team).State = EntityState.Deleted;
            await db.SaveChangesAsync();
            return RedirectToAction($"Details/{team.LeagueId}");
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Backend/Backend/Views/Leagues/Create.cshtml
@model Backend.Models.LeagueView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Leagues",FormMethod.Post, new { enctype ="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>League</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 ">
                <div class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.LogoFile, new { type="file" })
                    @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Backend/Views/Leagues/CreateTeam.cshtml
@model Backend.Models.TeamView

@{
    ViewBag.Title = "CreateTeam";
}

<h2>CreateTeam</h2>


@using (Html.BeginForm("CreateTeam", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(t=> t.LeagueId)
    
    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 ">
                <div class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.LogoFile, new { type = "file" })
                    @Html.ValidationMessageFor(model => model.LogoFile, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to League",$"Details/{Model.LeagueId}")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Backend/Views/Leagues/Delete.cshtml
@model Dominio.League

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Backend/Backend/Views/Leagues/Details.cshtml
@model Dominio.League

@{
    ViewBag.Title = "Details";
}

<h2>League</h2>

<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:150;max-width:100%;min-height:100%" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LeagueId }) |
    @Html.ActionLink("Crearte to Team", "CreateTeam", new { id = Model.LeagueId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>Team</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Logo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Initials)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Teams)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Logo))
                {
                    <img src="@Url.Content(item.Logo)" alt="Image" style="width:100px;height:150;max-width:100%;min-height:100%" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Initials)
            </td>
            <td>
                @Html.ActionLink("Edit Team", "EditTeam", new { id = item.TeamId }) |
                @Html.ActionLink("Details Team", "DetailsTeam", new { id = item.TeamId }) |
                @Html.ActionLink("Delete Team", "DeleteTeam", new { id = item.TeamId },new { @onclick = "return confirm('Areyou sure to delete this record?');" })
            </td>
        </tr>
    }

</table>

Backend/Backend/Views/Leagues/DetailsTeam.cshtml
@model Dominio.Team

@{
    ViewBag.Title = "DetailsTeam";
}

<h2>Details Team</h2>

<div>
    <h4>Team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.League.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.League.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:150;max-width:100%;min-height:100%" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Initials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Initials)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit Team", "EditTeam", new { id = Model.TeamId }) |
    @Html.ActionLink("Back to League", $"Details/{Model.LeagueId}")
</p>

Backend/Backend/Views/Leagues/Edit.cshtml
@model Backend.Models.LeagueView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Leagues",FormMethod.Post,new { enctype= "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>League</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.LeagueId)
    @Html.HiddenFor(model => model.Logo)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ">
            <div class="btn btn-default btn-file">
                @Html.TextBoxFor(model => model.LogoFile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Backend/Views/Leagues/EditTeam.cshtml
@model Backend.Models.TeamView

@{
    ViewBag.Title = "EditTeam";
}

<h2>EditTeam</h2>


@using (Html.BeginForm("EditTeam", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(t => t.LeagueId)
    @Html.HiddenFor(t => t.Logo)
    @Html.HiddenFor(t => t.Visitors)
    @Html.HiddenFor(t => t.TournamentTeams)
    @Html.HiddenFor(t => t.League)

    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 ">
                <div class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.LogoFile, new { type = "file" })
                    @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to League", $"Details/{Model.LeagueId}")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Backend/Views/Leagues/Index.cshtml
@model IEnumerable<Dominio.League>

@{
    ViewBag.Title = "League";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Logo))
            {
                <img src="@Url.Content(item.Logo)" alt="Image" style="width:100px;height:150;max-width:100%;min-height:100%" />
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LeagueId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LeagueId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LeagueId })
        </td>
    </tr>
}

</table>